### PR TITLE
Add patch to fix X455LB touchpad issue

### PR DESCRIPTION
**Pull request by leledumbo**
This patch will prevent touchpad in ASUS X455LB from hanging after resuming from suspend due to self test procedure.

### CODE REVIEW

**Comment by korrode** [comment]
A great deal of this patch is whitespace changes only, like someone converted to and from tabs in their text editor or whatever. From what i can see there's no need for the patch to be anywhere near 2000+ lines long, please provide a cleaner patch. Also if there's LKML/etc. discussion about this issue, please link to it.

**Comment by philmmanjaro** [comment]
@leledumbo: as @korrode already pointed out I see mostly whitespace changes and not the actual change. How did you create that patch? More or less you only change what is needed. Patching to much will create issues with upstream patches coming along. So did you do the patch on your own or came it from upstream? Then I need the discussion and actual commit to integrate it.

**Comment by leledumbo** [comment]
It was created by adding the lines by hand, then git diff. But it looks like my text editor messes up with the indentation. I'll try creating a cleaner one.

**Comment by mirh** [comment]
Wasn't this [already](https://forum.manjaro.org/index.php?topic=31240.0#msg264631) included?

**Comment by leledumbo** [comment]
@mirh nope, see relevant paragraph in the first post. I patch the kernel then build it myself, only for my system. I have problem now since manjaro repo is already way ahead of stable, thus I need to build not only the kernel but also other modules that I use (they're in incompatible state ATM), including the important nvidia and virtualbox host modules. If it's integrated in the repo, next stable I don't have to rebuild anything so there won't be any module incompatibility issue anymore.

**Comment by mirh** [comment]
Oh, lol, right. I didn't realize the last post author and OP were the same person. 
Besides, what's stopping you from sending this upstream?

**Comment by leledumbo** [comment]
Because this patch is not originally written by me, which the author unsure whether skipping the self test call has any consequences or not (I found none so far, though). I just adjust it so that it can be merged into kernel 4.4 and newer. Original post including patch: https://marc.info/?l=linux-input&m=144312209020616&w=2

**Comment by philmmanjaro** [comment]
Why create a new patch then and not use the original draft patch? However, did you asked the author why nobody picked it up at all?

**Comment by leledumbo** [comment]
> Why create a new patch then and not use the original draft patch?

Tried it previously, patching failed. I guess it's just line number problems, but still better let git make the correction than my eyes + hand which obviously has bigger chance of making mistakes.

> However, did you asked the author why nobody picked it up at all?

Nope, not yet.

**Comment by philmmanjaro** [comment]
If I review the original patch and yours, then I noticed that you missed to import one header file. If there is any issue with the patch you will find a regression file you can post. With this we can backport the patch properly. Since the patch is from September 2015 kernels with 4.2+ might have this issue also. I assume you're using **linux44** as your main kernel as of now. It would be great to know what happened to the patch and why it was never merged. On first view I see no regressions to implement it.

**Comment by leledumbo** [comment]
> If I review the original patch and yours, then I noticed that you missed to import one header file.

Oops. But it still compiles, I guess it's implicitly #include-d by some other #include-d headers. Do you want me to explicitly add it?

> If there is any issue with the patch you will find a regression file you can post. With this we can backport the patch properly.

There's none for my patch. Do you mean for the original patch?

> Since the patch is from September 2015 kernels with 4.2+ might have this issue also.

4.1 and before as well. The first working module for this touchpad appears in late 2014 / early 2015, in kernel 3.19 / 4.0 if I'm not mistaken, since that time this self test hanging issue has never been fixed.

> I assume you're using linux44 as your main kernel as of now.

4.5 :)

> It would be great to know what happened to the patch and why it was never merged.

I guess the author never send it upstream.

> On first view I see no regressions to implement it.

So do I. The patch is rather small and does checking for the specific laptop model, so any other devices shouldn't be affected. Unless there's a bug in `dmi_check_system` (VERY unlikely) that returns true even for devices not in the given blacklist.

**Comment by philmmanjaro** [comment]
Yes I meant the original patch. Always try to patch it and if it doesn't work you get a result for review. I've to review it again to see what can be done with it. Did you ever talked to the maintainer of the module about this patch? He might give you some tips on how to get it upstream. I've to check if I can implement it for Manjaro as it is now.

**Comment by philmmanjaro** [comment]
Please contact [Vojtech Pavlik](mailto:vojtech@suse.cz) (module maintainer) and [John Hiesey](john@hiesey.com) (patch creator) about this patch. I did another review and nothing speaks against it to be included. However we should respect John's work and include the original patch somehow. So try to use the original patch and post me the regression you may have. Then we can rebase the patch.

**Comment by leledumbo** [comment]
> Yes I meant the original patch. Always try to patch it and if it doesn't work you get a result for review. I've to review it again to see what can be done with it

Here it is: [i8042.c.rej.zip](https://github.com/manjaro/packages-core/files/255759/i8042.c.rej.zip) (fake .zip extension, just remove it)
Practically, it's the same as mine, really only differs in line numbers.

> Please contact Vojtech Pavlik (module maintainer) and John Hiesey (patch creator) about this patch

OK, I'll do it later. It's almost 3 a.m. now here. I'll contact them after I get some sleep.

**Comment by leledumbo** [comment]
No response so far from any of them

**Comment by philmmanjaro** [comment]
Which kernels do have this issue and to which should we apply the patch if?

**Comment by leledumbo** [comment]
Practically all currently maintained kernels, however I only test this patch against 4.4-4.6. My guess is that it should work for 4.1-4.2 as well, but not for 3.X series.

**Comment by philmmanjaro** [comment]
So 4.x series then.

**Comment by leledumbo** [comment]
Finally a reply from John:

> Hi Mario, I did send the patch to the mailing list, but I got busy and never followed up on getting this patch upstreamed.

> There’s no reason it shouldn’t be in the mainline kernel from my side. Feel free to do so.

> John

**Comment by philmmanjaro** [comment]
@leledumbo: forward this email to me, also I need to know for which kernel series we want to have it. Do we need it from 4.0 on or when was this regression introduced? With that information I can start to create a patch for each kernel we should apply it.

**Comment by leledumbo** [comment]
I can't seem to find your email, neither here nor the forum.

**Comment by philmmanjaro** [comment]
try [this one](mailto:philm@manjaro.org).

**Comment by leledumbo** [comment]
Slap me on the face. I didn't set up the autocomplete in my email client correctly, now your email is found and John's email has been forwarded to you.

**Comment by philmmanjaro** [comment]
@leledumbo: added now to **linux46**: https://github.com/manjaro/packages-core/commit/4a3bd4cf7535d17edd11257583e7026acd9b41ea. To which other series should I apply the patch?

**Comment by leledumbo** [comment]
4.4-4.5 please, at least 4.4 since it's LTS.

**Comment by philmmanjaro** [comment]
Which was the first kernel introducing it? Was it with 3.x series already?

**Comment by leledumbo** [comment]
As written above, 3.19 / 4.0.

**Comment by philmmanjaro** [comment]
This patch is now also added to 4.4 and 4.5.

**Comment by leledumbo** [comment]
Alright, thanks Phil.

**Comment by philmmanjaro** [comment]
Currently this patch is included in:

linux41 linux44 linux45  linux46 linux47

**Comment by leledumbo** [comment]
branch-wise, will the next stable has it? if so, we can close this PR.

**Comment by philmmanjaro** [comment]
**16.06** has this patch already included since development state.

**Comment by leledumbo** [comment]
hmm? why does my touchpad still die after sleep then? I've gotta check your commit. probably the dmi value is incorrect.

**Comment by philmmanjaro** [comment]
I'm [applying](https://github.com/manjaro/packages-core/blob/master/linux44/PKGBUILD#L99) the [patch](https://github.com/manjaro/packages-core/blob/master/linux44/i8042-asus-x455lab-dmi.patch) as given ...

**Comment by leledumbo** [comment]
Correct me if I'm wrong. `dmidecode` on my machine returns "X455LB", while the corresponding noselftest table entry in your patch is `DMI_MATCH(DMI_PRODUCT_NAME, "X455LAB"),` (in your patch). The search is done using `strstr`, which searches matches for "X455LAB" in "X455LB" which of course, returns false. In my patch, it's explicitly stated as ["X455LB"](https://github.com/leledumbo/packages-core/blob/03a5fa9ba5bdd20e18c98d524a3e4dda02621df5/linux44/i8042.patch#L35). Actually, X455LAB sounds weird since there's no X455LAB in ASUS website. There are X455LA, X455LB and X455LD only.

**Comment by philmmanjaro** [comment]
I applied the [original patch](https://marc.info/?l=linux-input&m=144312209020616&w=2). Then it is clear that if you search for another pattern that it fails.

**Comment by leledumbo** [comment]
So what to do now in order to change it to the correct value? It's just an easy 2 char deletion (just put X455L instead of X455LAB, it will cover all X455L family which differs only in processor, graphics card and storage), but if you insist on using the original patch, something must be done, right?

**Comment by leledumbo** [comment]
OK, at least my own model is supported. I'm closing this PR.

**Comment by philmmanjaro** [comment]
Seems there is a new upstream patch for this: https://github.com/torvalds/linux/commit/930e19248e9b61da36c967687ca79c4d5f977919

**Comment by leledumbo** [comment]
> Seems there is a new upstream patch for this: torvalds/linux@930e192

My model is not listed in the table. How should I propose it upstream (so that you don't have to maintain the patch anymore)?

**Comment by mirh** [comment]
Tell [these guys](https://bugzilla.kernel.org/show_bug.cgi?id=107971).

**Comment by philmmanjaro** [comment]
@leledumbo: seems the [patch](http://www.spinics.net/lists/kernel/msg2369800.html) gets now adopted by the other kernel trees as given. Seems your model is therefore not given anymore. Any update on the matter?

**Comment by philmmanjaro** [comment]
@leledumbo: was this [extra patch](https://bugzilla.kernel.org/attachment.cgi?id=242001&action=diff&context=patch&collapsed=&headers=1&format=raw) already successfully tested from your end?

**Comment by leledumbo** [comment]
No, I haven't. There was a change not to list any model, but simply apply it to all ASUS laptop.

**Comment by philmmanjaro** [comment]
Please test **linux44-4.4.27-2** package, which includes that proposed patch and give me feedback.

**Comment by philmmanjaro** [comment]
Ok. Then it works. Yes **4.4.28-2** which is actually **4.4.29** has that patch also added. I'll adopt it when needed to all other kernels. Thx for your feedback.

**Comment by leledumbo** [comment]
Not really want to reopen this, just FYI, kernel 4.9 lacks the patch so it's broken again for my device. A [final proper fix](http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=77b425399f6d5f1b04c58738bc10ca6decb10c9a) seems to have been submitted and accepted to master but no idea which version will have it for the first time since it's not even in HEAD of 4.9.y.

**Comment by mirh** [comment]
It's included in 4.10 https://github.com/torvalds/linux/commit/77b425399f6d5f1b04c58738bc10ca6decb10c9a

**Comment by leledumbo** [comment]
> It's included in 4.10 torvalds/linux@77b4253

Good to know, thanks.

**Comment by philmmanjaro** [comment]
Excellent ... :smile:

**Pull request closed without merging**
