### PR TITLE
Add first script for warning support when kernel update/install/remove

### PR DESCRIPTION
**Pull request by Ste74**
@philmmanjaro , @oberon2007 , @Kirek please check if is a good idea .. no build yet before your approvation
This is the request and i think have sense :p
https://forum.manjaro.org/t/reboot-required-notifier/29809

### CODE REVIEW

**Comment by oberon2007** [comment]
Sure. Why not. One could assume that people would be grown-up to decide for themselves but why not 😉 
Although I would maybe change the text a little. It's not necessarily true that a reboot is 'required'.
Maybe we could say something like.
"Kernel has been updated. It is advisable to reboot the computer. Remember to save your work first."
Or somthing like that ....
One more remark btw: Rebooting only makes sense if the currently **running** kernel has received an update ... 😜

**Comment by Ste74** [comment]
> Sure. Why not. One could assume that people would be grown-up enough to decide for themselves but why not 😉

true but more are lazy people 😉 

> Although I would maybe change the text a little. It's not necessarily true that a reboot is 'required'.
> Maybe we could say something like.
> "Kernel has been updated. It is advisable to reboot the computer. Remember to save your work first."
> Or somthing like that ....
> 
Yep i like it

> One more remark btw: Rebooting only makes sense if the currently running kernel has received an update ... 😜

true but how to check this ?` uname -r ` write the kernel in use and `ls /boot/ | grep vmlinuz ` write the vmlinuz* series installed .. how combine that ? 
Uhmm is also possible use mhwd-kenel -li to print the kernel in use ( ex linux412 )

**Comment by Ste74** [comment]
@jonathonf , first of all thank you. I have tested now the hook : updated the kernel now and the hook work only we have to change strategy because the notify not showing ( remember the problem of security when i build aur support pkgs ; i think is the same .. at this point we have to switch on a systemd service to check this or use a inotifywait service :p

**Comment by Ste74** [comment]
Well ,change approach, i will build a separate package with some ideas found on the reddit by @jonathonf

**Comment by Ste74** [comment]
well , change approach, i will build a separate package with some ideas found on the net by @jonathonf

**Pull request closed without merging**
