### PR TITLE
Rt

### PR DESCRIPTION
**Pull request by budimanjojo**
Can I get a new branch for my rt kernel patches? Also want to know why can't I compile without disabling the aufs patches, what do I have to change to make it possible?  Thanks before guys 👍

### CODE REVIEW

**Comment by philmmanjaro** [comment]
We won't merge this. Please use it in your own fork.

**Comment by budimanjojo** [comment]
I wasn't asking it to be merged in the master branch, I was asking for a new bramch. But I can't make a pull request on a branch that isn't created yet in github.
Do I have a better chance if I make a new package named linuxrt with the required extramodules in packages/community repository? I'll maintain it with the latest stable kernel.

**Comment by philmmanjaro** [comment]
Ok, what is the gain out of this? You want to add a real time kernel to Manjaro and add it to our repositories. Also you want to become a Manjaro packager and therefore want to join our packagers team? We have to find a name for the package and integrate it to Manjaro. Also all extramodules need to been built in **i686** and **x86_64**. I'd recommend to maintain one kernel. First fork our repository and then add there your changes. Merging would be then more possible as we don't have branches for our packages repositories.

**Comment by budimanjojo** [comment]
Okay, thanks. I think I'll make a PKGBUILD based off https://aur.archlinux.org/packages/linux-rt/ but I'll modify it to use Manjaro patches and will push it into manjaro/community repository with all the extramodules for it. I'll name it linuxrt and the extramodules will be linuxrt-extramodules. Is that good?

**Comment by budimanjojo** [comment]
Hi, philm. I have actually done making the packages, I wonder where's the right place for me to make a pull request. Should I put it in the packages-core or packages-community? Here's the code if you can take a look at it: https://github.com/budimanjojo/manjaro-rt
Thanks before.

**Comment by philmmanjaro** [comment]
@budimanjojo: Ok step one is done. I assume you have also built the packages against our stable branch? If so you can create a local user-repository using [repo-add](https://www.archlinux.org/pacman/repo-add.8.html) with the usual repository structure for **i686** and **x86_64**. Then you can use for example **dropbox** to create an online repository from it. Then we can discuss on how we can integrate your packages officially into **Manjaro Linux**. The **community** repository will be the place then for them.

**Comment by budimanjojo** [comment]
Yeah it's based on the lts kernel linux4.4.13 in the stable branch. I can build the required packages for both i686 and x86_64, but my upload speed is so slow that I don't think I got the time to upload them. Is this how packages in the community works? Can I get somebody to build and upload it for me?

**Comment by philmmanjaro** [comment]
Ok, so you want to maintain the **PKGBUILD**s but you need a build server for it. OpenSuse supports Archlinux. Maybe it works like that. Else open a topic in our forum [here](https://forum.manjaro.org/c/technical-issues-and-assistance/kernel) and ask around.

**Comment by budimanjojo** [comment]
Okay, right now I found out there's a bug with nvidia proprietary on rt kernels. I'll try to find a fix for it and fix some typos first. Changed the kernel base to 4.6 and haven't test it out yet. Is there any known friendly packager in the community repository? Or they are all packaging only their own packages there?

**Comment by korrode** [comment]
To keep with common AUR/Arch/Manjaro naming conventions, i'd suggest calling the package "linux-rt-manjaro", rather than "linuxrt".

**Comment by korrode** [comment]
...also i'm not so sure Manjaro has attracted enough audio engineers to warrant a RT kernel in the repos...

**Comment by budimanjojo** [comment]
Okay, I'll change the name later. I'm sure there are audio engineers using Manjaro out there. At least I found one: https://forum.manjaro.org/t/several-issues/2520/45
:)

**Comment by budimanjojo** [comment]
Naming modified as of these patches:
https://github.com/budimanjojo/manjaro-rt/commit/5fa353ece4c23c55c5bea02d514fa6e0d52c8de1
https://github.com/budimanjojo/manjaro-rt/commit/c52fbff9230c7e1541ca08c04075cc551e385ca6
I'll make a pull request to the community package now :)

**Pull request closed without merging**
