### PR TITLE
Export LC_ALL from locale.conf

### PR DESCRIPTION
**Pull request by agur4ik**
Without this I have multiple warnings from almost any executables in Manjaro-unstable even
though locale is generated by locale-gen and all locale vars are set in /etc/locale.conf. 

Maybe it is fixable in other way, as this file was quite forever in this state and I didn't ever have such warnings in Arch Linux.

### CODE REVIEW

**Comment by philmmanjaro** [comment]
I'll check the difference and most likely merge it.

**Comment by philmmanjaro** [comment]
The locale set for `LC_ALL` will always override `LANG` and all the other `LC_*` variables, whether they are set or not.

`LC_ALL` is the only `LC_*` variable, which **CAN'T** be set in `locale.conf` files: it is meant to be used only for testing or troubleshooting purposes, for example in `/etc/profile`.

**Comment by oberon2007** [comment]
> multiple warnings from almost any executables

I haven't seen such warnings, yet. Do you have an example how to reproduce the issue?

**Comment by philmmanjaro** [comment]
might be obsolete with https://github.com/manjaro/packages-core/commit/a08e0b19cc95022eca8269a9c120aa2ef53fef6b

**Comment by agur4ik** [comment]
@philmmanjaro After a08e0b1 I'm experiencing these warnings again. But it appears to be KDE issue since no warnings in tty console. I'll make further investigation to find the root of the issue. But that is offtop here, so I'm closing this PQ.

**Pull request closed without merging**
