### PR TITLE
use the new manjaro logo for grub, grub-quiet background

### PR DESCRIPTION
**Pull request by Tids**

### CODE REVIEW

**Comment by Ste74** [comment]
Hi .. changed also the dark background ?

**Comment by philmmanjaro** [comment]
I also was wondering why the background colour had changed ...

**Comment by oberon2007** [comment]
For my taste it seems more logical to keep the black for a seamless and homogenous context of the whole boot process. Typically you get a black background with some kind of a splash logo first, then the grub screen and then either a plymouth with a black background, or text on black... :wink:

**Comment by Tids** [comment]
Good point. I'll re-do it with completely black background

**Comment by oberon2007** [comment]
Thanks! :)

**Pull request merged**
